
import java.awt.CardLayout;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Bruno
 */
public class OpeningForm extends javax.swing.JFrame {

    /**
     * Creates new form OpeningForm
     */
    
    // Create the preset levels
    Level e1 = new Level("1E","Easy","+",3,6,7,5,8,11,12,6,9,12,13,9,12,15,16);
    Level e2 = new Level("2E","Easy","+",5,8,1,7,12,15,8,6,11,14,7,3,8,11,4);
    Level e3 = new Level("3E","Easy","+",3,5,8,8,11,13,16,6,9,11,14,4,7,9,12);
    Level e4 = new Level("4E","Easy","+",7,8,9,4,11,12,13,8,15,16,17,3,10,11,12);
    Level e5 = new Level("5E","Easy","+",12,14,17,18,30,32,35,21,33,35,38,35,47,49,52);
    Level e6 = new Level("6E","Easy","+",21,32,42,40,61,72,82,27,48,59,69,38,59,70,80);
    Level e7 = new Level("7E","Easy","-",9,8,11,3,6,5,8,4,5,4,7,1,8,7,10);
    Level e8 = new Level("8E","Easy","-",15,23,41,7,8,16,34,12,3,11,29,4,11,19,37);
    Level h1 = new Level("1H","Hard","+",11,15,25,23,6,8,9,10,1,2,7,18,4,5,9);
    Level h2 = new Level("2H","Hard","+",29,26,21,29,12,9,8,34,14,13,7,13,3,4,6);
    Level h3 = new Level("3H","Hard","+",60,63,55,49,14,17,18,65,21,23,21,64,25,23,16);
    Level h4 = new Level("4H","Hard","+",84,72,49,67,21,32,14,64,29,18,17,74,34,22,18);
    Level h5 = new Level("5H","Hard","+",31,96,42,32,14,10,8,77,4,41,32,60,13,45,2);
    Level h6 = new Level("6H","Hard","+",89,89,91,99,45,51,3,83,32,5,46,87,12,33,42);
    Level h7 = new Level("7H","Hard","+",69,71,71,50,23,13,14,68,41,2,25,93,5,56,32);
    Level h8 = new Level("8H","Hard","+",58,97,72,99,12,62,25,68,32,12,24,60,14,23,23);
    Level level;
    
    // Create database object
    Database db = new Database();
    
    // Create player object variable
    Player player;
    
    // Create boolean to know if player if logged in
    Boolean isLogged = false;
    
    public OpeningForm() {
        initComponents();
        // Set image to window icon
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Logo.png")));
        
        // Start window in the middle of the screen
        this.setLocationRelativeTo(null);
        
        // Make sure the program always starts on the main menu
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "openingMenuPanel");     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        levelPanel = new javax.swing.JPanel();
        goBackBtn = new javax.swing.JButton();
        signSquare = new javax.swing.JTextField();
        number1Square = new javax.swing.JTextField();
        number2Square = new javax.swing.JTextField();
        number3Square = new javax.swing.JTextField();
        number4Square = new javax.swing.JTextField();
        number5Square = new javax.swing.JTextField();
        number6Square = new javax.swing.JTextField();
        number7Square = new javax.swing.JTextField();
        number8Square = new javax.swing.JTextField();
        number9Square = new javax.swing.JTextField();
        number10Square = new javax.swing.JTextField();
        number11Square = new javax.swing.JTextField();
        number12Square = new javax.swing.JTextField();
        number13Square = new javax.swing.JTextField();
        number14Square = new javax.swing.JTextField();
        number15Square = new javax.swing.JTextField();
        checkBtn = new javax.swing.JButton();
        levelInformationLabel = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        backgroundLevelPanel = new javax.swing.JLabel();
        openingMenuPanel = new javax.swing.JPanel();
        easyBtn = new javax.swing.JButton();
        hardBtn = new javax.swing.JButton();
        logInPanelBtn = new javax.swing.JButton();
        logInLabel = new javax.swing.JLabel();
        backgroundOMImage = new javax.swing.JLabel();
        hardLevelsPanel = new javax.swing.JPanel();
        level1Btn1 = new javax.swing.JButton();
        level2Btn1 = new javax.swing.JButton();
        level3Btn1 = new javax.swing.JButton();
        level4Btn1 = new javax.swing.JButton();
        level6Btn1 = new javax.swing.JButton();
        level5Btn1 = new javax.swing.JButton();
        level7Btn1 = new javax.swing.JButton();
        level8Btn1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        backgroundELImage1 = new javax.swing.JLabel();
        easyLevelsPanel = new javax.swing.JPanel();
        level1Btn = new javax.swing.JButton();
        level2Btn = new javax.swing.JButton();
        level3Btn = new javax.swing.JButton();
        level4Btn = new javax.swing.JButton();
        level5Btn = new javax.swing.JButton();
        level6Btn = new javax.swing.JButton();
        level7Btn = new javax.swing.JButton();
        level8Btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        backgroundELImage = new javax.swing.JLabel();
        logInPanel = new javax.swing.JPanel();
        usernameLogInPanel = new javax.swing.JLabel();
        usernameTxtLogInPanel = new javax.swing.JTextField();
        passwordLogInPanel = new javax.swing.JLabel();
        passwordTxtLogInPanel = new javax.swing.JPasswordField();
        logInBtn = new javax.swing.JButton();
        registerPanelBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        backgroundLogInImage = new javax.swing.JLabel();
        profilePanel = new javax.swing.JPanel();
        countryFlag = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        e1Unlocked = new javax.swing.JLabel();
        e2Unlocked = new javax.swing.JLabel();
        e3Unlocked = new javax.swing.JLabel();
        e4Unlocked = new javax.swing.JLabel();
        e5Unlocked = new javax.swing.JLabel();
        e6Unlocked = new javax.swing.JLabel();
        e7Unlocked = new javax.swing.JLabel();
        e8Unlocked = new javax.swing.JLabel();
        h1Unlocked = new javax.swing.JLabel();
        h2Unlocked = new javax.swing.JLabel();
        h3Unlocked = new javax.swing.JLabel();
        h4Unlocked = new javax.swing.JLabel();
        h5Unlocked = new javax.swing.JLabel();
        h6Unlocked = new javax.swing.JLabel();
        h7Unlocked = new javax.swing.JLabel();
        h8Unlocked = new javax.swing.JLabel();
        playedTxt = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        wonTxt = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        percentageTxt = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        backgroundProfileImage = new javax.swing.JLabel();
        registerPanel = new javax.swing.JPanel();
        usernameLogInPanel1 = new javax.swing.JLabel();
        usernameTxtLogInPanel1 = new javax.swing.JTextField();
        passwordLogInPanel1 = new javax.swing.JLabel();
        passwordTxtLogInPanel1 = new javax.swing.JPasswordField();
        registerPanelBtn1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        backgroundLogInImage1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Math Tables");
        setName("form"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(800, 800));

        mainPanel.setLayout(new java.awt.CardLayout());

        levelPanel.setLayout(null);

        goBackBtn.setBackground(new java.awt.Color(0, 0, 204));
        goBackBtn.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        goBackBtn.setForeground(new java.awt.Color(255, 255, 255));
        goBackBtn.setText("Level Select");
        goBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackBtnActionPerformed(evt);
            }
        });
        levelPanel.add(goBackBtn);
        goBackBtn.setBounds(470, 60, 200, 50);

        signSquare.setBackground(new java.awt.Color(0, 0, 204));
        signSquare.setFont(new java.awt.Font("Arial", 1, 100)); // NOI18N
        signSquare.setForeground(new java.awt.Color(255, 255, 255));
        signSquare.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signSquare.setText("+");
        signSquare.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        levelPanel.add(signSquare);
        signSquare.setBounds(70, 250, 100, 100);

        number1Square.setBackground(new java.awt.Color(255, 255, 255));
        number1Square.setFont(new java.awt.Font("Arial", 1, 75)); // NOI18N
        number1Square.setForeground(new java.awt.Color(0, 0, 0));
        number1Square.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number1Square.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        levelPanel.add(number1Square);
        number1Square.setBounds(180, 250, 100, 100);

        number2Square.setBackground(new java.awt.Color(255, 255, 255));
        number2Square.setFont(new java.awt.Font("Arial", 1, 75)); // NOI18N
        number2Square.setForeground(new java.awt.Color(0, 0, 0));
        number2Square.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number2Square.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        levelPanel.add(number2Square);
        number2Square.setBounds(290, 250, 100, 100);

        number3Square.setBackground(new java.awt.Color(255, 255, 255));
        number3Square.setFont(new java.awt.Font("Arial", 1, 75)); // NOI18N
        number3Square.setForeground(new java.awt.Color(0, 0, 0));
        number3Square.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number3Square.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        levelPanel.add(number3Square);
        number3Square.setBounds(400, 250, 100, 100);

        number4Square.setBackground(new java.awt.Color(255, 255, 255));
        number4Square.setFont(new java.awt.Font("Arial", 1, 75)); // NOI18N
        number4Square.setForeground(new java.awt.Color(0, 0, 0));
        number4Square.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number4Square.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        levelPanel.add(number4Square);
        number4Square.setBounds(70, 360, 100, 100);

        number5Square.setBackground(new java.awt.Color(0, 0, 204));
        number5Square.setFont(new java.awt.Font("Arial", 1, 75)); // NOI18N
        number5Square.setForeground(new java.awt.Color(255, 255, 255));
        number5Square.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number5Square.setText("88");
        levelPanel.add(number5Square);
        number5Square.setBounds(180, 360, 100, 100);

        number6Square.setBackground(new java.awt.Color(0, 0, 204));
        number6Square.setFont(new java.awt.Font("Arial", 1, 75)); // NOI18N
        number6Square.setForeground(new java.awt.Color(255, 255, 255));
        number6Square.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number6Square.setText("2");
        levelPanel.add(number6Square);
        number6Square.setBounds(290, 360, 100, 100);

        number7Square.setBackground(new java.awt.Color(0, 0, 204));
        number7Square.setFont(new java.awt.Font("Arial", 1, 75)); // NOI18N
        number7Square.setForeground(new java.awt.Color(255, 255, 255));
        number7Square.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number7Square.setText("3");
        number7Square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number7SquareActionPerformed(evt);
            }
        });
        levelPanel.add(number7Square);
        number7Square.setBounds(400, 360, 100, 100);

        number8Square.setBackground(new java.awt.Color(255, 255, 255));
        number8Square.setFont(new java.awt.Font("Arial", 1, 75)); // NOI18N
        number8Square.setForeground(new java.awt.Color(0, 0, 0));
        number8Square.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number8Square.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        levelPanel.add(number8Square);
        number8Square.setBounds(70, 470, 100, 100);

        number9Square.setBackground(new java.awt.Color(0, 0, 204));
        number9Square.setFont(new java.awt.Font("Arial", 1, 75)); // NOI18N
        number9Square.setForeground(new java.awt.Color(255, 255, 255));
        number9Square.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number9Square.setText("4");
        levelPanel.add(number9Square);
        number9Square.setBounds(180, 470, 100, 100);

        number10Square.setBackground(new java.awt.Color(0, 0, 204));
        number10Square.setFont(new java.awt.Font("Arial", 1, 75)); // NOI18N
        number10Square.setForeground(new java.awt.Color(255, 255, 255));
        number10Square.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number10Square.setText("5");
        levelPanel.add(number10Square);
        number10Square.setBounds(290, 470, 100, 100);

        number11Square.setBackground(new java.awt.Color(0, 0, 204));
        number11Square.setFont(new java.awt.Font("Arial", 1, 75)); // NOI18N
        number11Square.setForeground(new java.awt.Color(255, 255, 255));
        number11Square.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number11Square.setText("6");
        levelPanel.add(number11Square);
        number11Square.setBounds(400, 470, 100, 100);

        number12Square.setBackground(new java.awt.Color(255, 255, 255));
        number12Square.setFont(new java.awt.Font("Arial", 1, 75)); // NOI18N
        number12Square.setForeground(new java.awt.Color(0, 0, 0));
        number12Square.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number12Square.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        levelPanel.add(number12Square);
        number12Square.setBounds(70, 580, 100, 100);

        number13Square.setBackground(new java.awt.Color(0, 0, 204));
        number13Square.setFont(new java.awt.Font("Arial", 1, 75)); // NOI18N
        number13Square.setForeground(new java.awt.Color(255, 255, 255));
        number13Square.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number13Square.setText("7");
        levelPanel.add(number13Square);
        number13Square.setBounds(180, 580, 100, 100);

        number14Square.setBackground(new java.awt.Color(0, 0, 204));
        number14Square.setFont(new java.awt.Font("Arial", 1, 75)); // NOI18N
        number14Square.setForeground(new java.awt.Color(255, 255, 255));
        number14Square.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number14Square.setText("8");
        levelPanel.add(number14Square);
        number14Square.setBounds(290, 580, 100, 100);

        number15Square.setBackground(new java.awt.Color(0, 0, 204));
        number15Square.setFont(new java.awt.Font("Arial", 1, 75)); // NOI18N
        number15Square.setForeground(new java.awt.Color(255, 255, 255));
        number15Square.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number15Square.setText("9");
        levelPanel.add(number15Square);
        number15Square.setBounds(400, 580, 100, 100);

        checkBtn.setBackground(new java.awt.Color(0, 0, 204));
        checkBtn.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        checkBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkBtn.setText("Check Answer");
        checkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBtnActionPerformed(evt);
            }
        });
        levelPanel.add(checkBtn);
        checkBtn.setBounds(510, 630, 230, 50);

        levelInformationLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        levelInformationLabel.setForeground(new java.awt.Color(0, 0, 0));
        levelInformationLabel.setText("<html>Level Information</html>\n");
        levelInformationLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        levelPanel.add(levelInformationLabel);
        levelInformationLabel.setBounds(510, 250, 230, 370);

        levelLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        levelLabel.setForeground(new java.awt.Color(0, 0, 0));
        levelLabel.setText("<html>Level [Difficulty/Number]</html>");
        levelPanel.add(levelLabel);
        levelLabel.setBounds(470, 110, 220, 70);

        backgroundLevelPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LevelBkg.png"))); // NOI18N
        levelPanel.add(backgroundLevelPanel);
        backgroundLevelPanel.setBounds(0, 0, 800, 800);

        mainPanel.add(levelPanel, "levelPanel");

        openingMenuPanel.setLayout(null);

        easyBtn.setBackground(new java.awt.Color(204, 0, 51));
        easyBtn.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        easyBtn.setForeground(new java.awt.Color(255, 255, 255));
        easyBtn.setText("Easy");
        easyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyBtnActionPerformed(evt);
            }
        });
        openingMenuPanel.add(easyBtn);
        easyBtn.setBounds(300, 410, 200, 50);

        hardBtn.setBackground(new java.awt.Color(0, 0, 255));
        hardBtn.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        hardBtn.setForeground(new java.awt.Color(255, 255, 255));
        hardBtn.setText("Hard");
        hardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardBtnActionPerformed(evt);
            }
        });
        openingMenuPanel.add(hardBtn);
        hardBtn.setBounds(300, 480, 200, 50);

        logInPanelBtn.setBackground(new java.awt.Color(204, 204, 0));
        logInPanelBtn.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        logInPanelBtn.setForeground(new java.awt.Color(255, 255, 255));
        logInPanelBtn.setText("Log In");
        logInPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInPanelBtnActionPerformed(evt);
            }
        });
        openingMenuPanel.add(logInPanelBtn);
        logInPanelBtn.setBounds(20, 690, 200, 50);

        logInLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        logInLabel.setForeground(new java.awt.Color(0, 0, 0));
        logInLabel.setText("<html>Log in to retrieve your progress<br/>or register to save your progress.</html>");
        logInLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        openingMenuPanel.add(logInLabel);
        logInLabel.setBounds(230, 690, 290, 50);

        backgroundOMImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OpeningBkg.png"))); // NOI18N
        openingMenuPanel.add(backgroundOMImage);
        backgroundOMImage.setBounds(0, 0, 800, 800);

        mainPanel.add(openingMenuPanel, "openingMenuPanel");

        hardLevelsPanel.setLayout(null);

        level1Btn1.setBackground(new java.awt.Color(0, 0, 204));
        level1Btn1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        level1Btn1.setForeground(new java.awt.Color(255, 255, 255));
        level1Btn1.setText("1");
        level1Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level1Btn1ActionPerformed(evt);
            }
        });
        hardLevelsPanel.add(level1Btn1);
        level1Btn1.setBounds(130, 340, 100, 100);

        level2Btn1.setBackground(new java.awt.Color(0, 0, 204));
        level2Btn1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        level2Btn1.setForeground(new java.awt.Color(255, 255, 255));
        level2Btn1.setText("2");
        level2Btn1.setEnabled(false);
        level2Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level2Btn1ActionPerformed(evt);
            }
        });
        hardLevelsPanel.add(level2Btn1);
        level2Btn1.setBounds(280, 340, 100, 100);

        level3Btn1.setBackground(new java.awt.Color(0, 0, 204));
        level3Btn1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        level3Btn1.setForeground(new java.awt.Color(255, 255, 255));
        level3Btn1.setText("3");
        level3Btn1.setEnabled(false);
        level3Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level3Btn1ActionPerformed(evt);
            }
        });
        hardLevelsPanel.add(level3Btn1);
        level3Btn1.setBounds(430, 340, 100, 100);

        level4Btn1.setBackground(new java.awt.Color(0, 0, 204));
        level4Btn1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        level4Btn1.setForeground(new java.awt.Color(255, 255, 255));
        level4Btn1.setText("4");
        level4Btn1.setEnabled(false);
        level4Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level4Btn1ActionPerformed(evt);
            }
        });
        hardLevelsPanel.add(level4Btn1);
        level4Btn1.setBounds(580, 340, 100, 100);

        level6Btn1.setBackground(new java.awt.Color(0, 0, 204));
        level6Btn1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        level6Btn1.setForeground(new java.awt.Color(255, 255, 255));
        level6Btn1.setText("6");
        level6Btn1.setEnabled(false);
        level6Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level6Btn1ActionPerformed(evt);
            }
        });
        hardLevelsPanel.add(level6Btn1);
        level6Btn1.setBounds(280, 480, 100, 100);

        level5Btn1.setBackground(new java.awt.Color(0, 0, 204));
        level5Btn1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        level5Btn1.setForeground(new java.awt.Color(255, 255, 255));
        level5Btn1.setText("5");
        level5Btn1.setEnabled(false);
        level5Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level5Btn1ActionPerformed(evt);
            }
        });
        hardLevelsPanel.add(level5Btn1);
        level5Btn1.setBounds(130, 480, 100, 100);

        level7Btn1.setBackground(new java.awt.Color(0, 0, 204));
        level7Btn1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        level7Btn1.setForeground(new java.awt.Color(255, 255, 255));
        level7Btn1.setText("7");
        level7Btn1.setEnabled(false);
        level7Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level7Btn1ActionPerformed(evt);
            }
        });
        hardLevelsPanel.add(level7Btn1);
        level7Btn1.setBounds(430, 480, 100, 100);

        level8Btn1.setBackground(new java.awt.Color(0, 0, 204));
        level8Btn1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        level8Btn1.setForeground(new java.awt.Color(255, 255, 255));
        level8Btn1.setText("8");
        level8Btn1.setEnabled(false);
        level8Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level8Btn1ActionPerformed(evt);
            }
        });
        hardLevelsPanel.add(level8Btn1);
        level8Btn1.setBounds(580, 480, 100, 100);

        jButton2.setBackground(new java.awt.Color(0, 0, 204));
        jButton2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Go back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        hardLevelsPanel.add(jButton2);
        jButton2.setBounds(130, 630, 200, 50);

        backgroundELImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LevelSelectionBkg.png"))); // NOI18N
        hardLevelsPanel.add(backgroundELImage1);
        backgroundELImage1.setBounds(0, 0, 800, 800);

        mainPanel.add(hardLevelsPanel, "hardLevelsPanel");

        easyLevelsPanel.setLayout(null);

        level1Btn.setBackground(new java.awt.Color(204, 0, 0));
        level1Btn.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        level1Btn.setForeground(new java.awt.Color(255, 255, 255));
        level1Btn.setText("1");
        level1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level1BtnActionPerformed(evt);
            }
        });
        easyLevelsPanel.add(level1Btn);
        level1Btn.setBounds(130, 340, 100, 100);

        level2Btn.setBackground(new java.awt.Color(204, 0, 0));
        level2Btn.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        level2Btn.setForeground(new java.awt.Color(255, 255, 255));
        level2Btn.setText("2");
        level2Btn.setEnabled(false);
        level2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level2BtnActionPerformed(evt);
            }
        });
        easyLevelsPanel.add(level2Btn);
        level2Btn.setBounds(280, 340, 100, 100);

        level3Btn.setBackground(new java.awt.Color(204, 0, 0));
        level3Btn.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        level3Btn.setForeground(new java.awt.Color(255, 255, 255));
        level3Btn.setText("3");
        level3Btn.setEnabled(false);
        level3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level3BtnActionPerformed(evt);
            }
        });
        easyLevelsPanel.add(level3Btn);
        level3Btn.setBounds(430, 340, 100, 100);

        level4Btn.setBackground(new java.awt.Color(204, 0, 0));
        level4Btn.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        level4Btn.setForeground(new java.awt.Color(255, 255, 255));
        level4Btn.setText("4");
        level4Btn.setEnabled(false);
        level4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level4BtnActionPerformed(evt);
            }
        });
        easyLevelsPanel.add(level4Btn);
        level4Btn.setBounds(580, 340, 100, 100);

        level5Btn.setBackground(new java.awt.Color(204, 0, 0));
        level5Btn.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        level5Btn.setForeground(new java.awt.Color(255, 255, 255));
        level5Btn.setText("5");
        level5Btn.setEnabled(false);
        level5Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level5BtnActionPerformed(evt);
            }
        });
        easyLevelsPanel.add(level5Btn);
        level5Btn.setBounds(130, 480, 100, 100);

        level6Btn.setBackground(new java.awt.Color(204, 0, 0));
        level6Btn.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        level6Btn.setForeground(new java.awt.Color(255, 255, 255));
        level6Btn.setText("6");
        level6Btn.setEnabled(false);
        level6Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level6BtnActionPerformed(evt);
            }
        });
        easyLevelsPanel.add(level6Btn);
        level6Btn.setBounds(280, 480, 100, 100);

        level7Btn.setBackground(new java.awt.Color(204, 0, 0));
        level7Btn.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        level7Btn.setForeground(new java.awt.Color(255, 255, 255));
        level7Btn.setText("7");
        level7Btn.setEnabled(false);
        level7Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level7BtnActionPerformed(evt);
            }
        });
        easyLevelsPanel.add(level7Btn);
        level7Btn.setBounds(430, 480, 100, 100);

        level8Btn.setBackground(new java.awt.Color(204, 0, 0));
        level8Btn.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        level8Btn.setForeground(new java.awt.Color(255, 255, 255));
        level8Btn.setText("8");
        level8Btn.setEnabled(false);
        level8Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level8BtnActionPerformed(evt);
            }
        });
        easyLevelsPanel.add(level8Btn);
        level8Btn.setBounds(580, 480, 100, 100);

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Go back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        easyLevelsPanel.add(jButton1);
        jButton1.setBounds(130, 630, 200, 50);

        backgroundELImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LevelSelectionBkg.png"))); // NOI18N
        easyLevelsPanel.add(backgroundELImage);
        backgroundELImage.setBounds(0, 0, 800, 800);

        mainPanel.add(easyLevelsPanel, "easyLevelsPanel");

        logInPanel.setLayout(null);

        usernameLogInPanel.setBackground(new java.awt.Color(0, 0, 0));
        usernameLogInPanel.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        usernameLogInPanel.setForeground(new java.awt.Color(0, 0, 0));
        usernameLogInPanel.setText("Username:");
        logInPanel.add(usernameLogInPanel);
        usernameLogInPanel.setBounds(180, 420, 180, 50);

        usernameTxtLogInPanel.setBackground(new java.awt.Color(255, 255, 255));
        usernameTxtLogInPanel.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        usernameTxtLogInPanel.setForeground(new java.awt.Color(0, 0, 0));
        logInPanel.add(usernameTxtLogInPanel);
        usernameTxtLogInPanel.setBounds(360, 422, 200, 50);

        passwordLogInPanel.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        passwordLogInPanel.setForeground(new java.awt.Color(0, 0, 0));
        passwordLogInPanel.setText("Password:");
        logInPanel.add(passwordLogInPanel);
        passwordLogInPanel.setBounds(190, 490, 170, 50);

        passwordTxtLogInPanel.setBackground(new java.awt.Color(255, 255, 255));
        passwordTxtLogInPanel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        passwordTxtLogInPanel.setForeground(new java.awt.Color(0, 0, 0));
        logInPanel.add(passwordTxtLogInPanel);
        passwordTxtLogInPanel.setBounds(360, 490, 200, 50);

        logInBtn.setBackground(new java.awt.Color(204, 0, 0));
        logInBtn.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        logInBtn.setForeground(new java.awt.Color(255, 255, 255));
        logInBtn.setText("Log In");
        logInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInBtnActionPerformed(evt);
            }
        });
        logInPanel.add(logInBtn);
        logInBtn.setBounds(360, 560, 200, 50);

        registerPanelBtn.setBackground(new java.awt.Color(0, 0, 204));
        registerPanelBtn.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        registerPanelBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerPanelBtn.setText("Register");
        registerPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPanelBtnActionPerformed(evt);
            }
        });
        logInPanel.add(registerPanelBtn);
        registerPanelBtn.setBounds(360, 620, 200, 50);

        jButton3.setBackground(new java.awt.Color(204, 204, 0));
        jButton3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Go Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        logInPanel.add(jButton3);
        jButton3.setBounds(30, 690, 200, 50);

        backgroundLogInImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OpeningBkg.png"))); // NOI18N
        logInPanel.add(backgroundLogInImage);
        backgroundLogInImage.setBounds(0, 0, 800, 770);

        mainPanel.add(logInPanel, "logInPanel");

        profilePanel.setLayout(null);

        countryFlag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countryFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UN.png"))); // NOI18N
        profilePanel.add(countryFlag);
        countryFlag.setBounds(130, 350, 75, 75);

        userNameLabel.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        userNameLabel.setText("UserName");
        profilePanel.add(userNameLabel);
        userNameLabel.setBounds(220, 350, 470, 70);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Levels Unlocked:");
        profilePanel.add(jLabel1);
        jLabel1.setBounds(130, 450, 190, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2");
        profilePanel.add(jLabel2);
        jLabel2.setBounds(230, 480, 30, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Easy");
        profilePanel.add(jLabel3);
        jLabel3.setBounds(130, 510, 50, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Hard");
        profilePanel.add(jLabel4);
        jLabel4.setBounds(130, 560, 50, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("3");
        profilePanel.add(jLabel5);
        jLabel5.setBounds(270, 480, 30, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("4");
        profilePanel.add(jLabel6);
        jLabel6.setBounds(310, 480, 30, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("5");
        profilePanel.add(jLabel7);
        jLabel7.setBounds(350, 480, 30, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("6");
        profilePanel.add(jLabel8);
        jLabel8.setBounds(390, 480, 30, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("7");
        profilePanel.add(jLabel9);
        jLabel9.setBounds(430, 480, 30, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("8");
        profilePanel.add(jLabel10);
        jLabel10.setBounds(470, 480, 30, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("1");
        profilePanel.add(jLabel11);
        jLabel11.setBounds(190, 480, 30, 30);

        e1Unlocked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GreenCircle.png"))); // NOI18N
        profilePanel.add(e1Unlocked);
        e1Unlocked.setBounds(190, 510, 30, 30);

        e2Unlocked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RedCircle.png"))); // NOI18N
        profilePanel.add(e2Unlocked);
        e2Unlocked.setBounds(230, 510, 30, 30);

        e3Unlocked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RedCircle.png"))); // NOI18N
        profilePanel.add(e3Unlocked);
        e3Unlocked.setBounds(270, 510, 30, 30);

        e4Unlocked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RedCircle.png"))); // NOI18N
        profilePanel.add(e4Unlocked);
        e4Unlocked.setBounds(310, 510, 30, 30);

        e5Unlocked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RedCircle.png"))); // NOI18N
        profilePanel.add(e5Unlocked);
        e5Unlocked.setBounds(350, 510, 30, 30);

        e6Unlocked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RedCircle.png"))); // NOI18N
        profilePanel.add(e6Unlocked);
        e6Unlocked.setBounds(390, 510, 30, 30);

        e7Unlocked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RedCircle.png"))); // NOI18N
        profilePanel.add(e7Unlocked);
        e7Unlocked.setBounds(430, 510, 30, 30);

        e8Unlocked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RedCircle.png"))); // NOI18N
        profilePanel.add(e8Unlocked);
        e8Unlocked.setBounds(470, 510, 30, 30);

        h1Unlocked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GreenCircle.png"))); // NOI18N
        profilePanel.add(h1Unlocked);
        h1Unlocked.setBounds(190, 560, 30, 30);

        h2Unlocked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RedCircle.png"))); // NOI18N
        profilePanel.add(h2Unlocked);
        h2Unlocked.setBounds(230, 560, 30, 30);

        h3Unlocked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RedCircle.png"))); // NOI18N
        profilePanel.add(h3Unlocked);
        h3Unlocked.setBounds(270, 560, 30, 30);

        h4Unlocked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RedCircle.png"))); // NOI18N
        profilePanel.add(h4Unlocked);
        h4Unlocked.setBounds(310, 560, 30, 30);

        h5Unlocked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RedCircle.png"))); // NOI18N
        profilePanel.add(h5Unlocked);
        h5Unlocked.setBounds(350, 560, 30, 30);

        h6Unlocked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RedCircle.png"))); // NOI18N
        profilePanel.add(h6Unlocked);
        h6Unlocked.setBounds(390, 560, 30, 30);

        h7Unlocked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RedCircle.png"))); // NOI18N
        profilePanel.add(h7Unlocked);
        h7Unlocked.setBounds(430, 560, 30, 30);

        h8Unlocked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RedCircle.png"))); // NOI18N
        profilePanel.add(h8Unlocked);
        h8Unlocked.setBounds(470, 560, 30, 30);

        playedTxt.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        playedTxt.setForeground(new java.awt.Color(0, 0, 0));
        playedTxt.setText("#");
        profilePanel.add(playedTxt);
        playedTxt.setBounds(520, 480, 190, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Games Played:");
        profilePanel.add(jLabel12);
        jLabel12.setBounds(520, 450, 190, 30);

        wonTxt.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        wonTxt.setForeground(new java.awt.Color(0, 0, 0));
        wonTxt.setText("#");
        profilePanel.add(wonTxt);
        wonTxt.setBounds(520, 550, 190, 30);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("of the games you played!");
        profilePanel.add(jLabel17);
        jLabel17.setBounds(520, 660, 210, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Games Won:");
        profilePanel.add(jLabel13);
        jLabel13.setBounds(520, 520, 190, 30);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("You won");
        profilePanel.add(jLabel16);
        jLabel16.setBounds(520, 600, 80, 20);

        percentageTxt.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        percentageTxt.setForeground(new java.awt.Color(0, 0, 0));
        percentageTxt.setText("100%");
        profilePanel.add(percentageTxt);
        percentageTxt.setBounds(520, 620, 200, 42);

        jButton4.setBackground(new java.awt.Color(204, 204, 0));
        jButton4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Go Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        profilePanel.add(jButton4);
        jButton4.setBounds(30, 690, 200, 50);

        backgroundProfileImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OpeningBkg.png"))); // NOI18N
        profilePanel.add(backgroundProfileImage);
        backgroundProfileImage.setBounds(0, 0, 800, 770);

        mainPanel.add(profilePanel, "profilePanel");

        registerPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        registerPanel.setLayout(null);

        usernameLogInPanel1.setBackground(new java.awt.Color(0, 0, 0));
        usernameLogInPanel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        usernameLogInPanel1.setForeground(new java.awt.Color(0, 0, 0));
        usernameLogInPanel1.setText("Username:");
        registerPanel.add(usernameLogInPanel1);
        usernameLogInPanel1.setBounds(180, 420, 180, 50);

        usernameTxtLogInPanel1.setBackground(new java.awt.Color(255, 255, 255));
        usernameTxtLogInPanel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        usernameTxtLogInPanel1.setForeground(new java.awt.Color(0, 0, 0));
        registerPanel.add(usernameTxtLogInPanel1);
        usernameTxtLogInPanel1.setBounds(360, 422, 200, 50);

        passwordLogInPanel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        passwordLogInPanel1.setForeground(new java.awt.Color(0, 0, 0));
        passwordLogInPanel1.setText("Password:");
        registerPanel.add(passwordLogInPanel1);
        passwordLogInPanel1.setBounds(190, 490, 170, 50);

        passwordTxtLogInPanel1.setBackground(new java.awt.Color(255, 255, 255));
        passwordTxtLogInPanel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        passwordTxtLogInPanel1.setForeground(new java.awt.Color(0, 0, 0));
        registerPanel.add(passwordTxtLogInPanel1);
        passwordTxtLogInPanel1.setBounds(360, 490, 200, 50);

        registerPanelBtn1.setBackground(new java.awt.Color(204, 0, 0));
        registerPanelBtn1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        registerPanelBtn1.setForeground(new java.awt.Color(255, 255, 255));
        registerPanelBtn1.setText("Register");
        registerPanelBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPanelBtn1ActionPerformed(evt);
            }
        });
        registerPanel.add(registerPanelBtn1);
        registerPanelBtn1.setBounds(360, 610, 200, 50);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("<html>By pressing register you agree that the program<br\\>will use you IP address to get your geolocation.<html\\>");
        registerPanel.add(jLabel14);
        jLabel14.setBounds(300, 570, 260, 30);

        jButton5.setBackground(new java.awt.Color(204, 204, 0));
        jButton5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Go Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        registerPanel.add(jButton5);
        jButton5.setBounds(30, 690, 200, 50);

        backgroundLogInImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OpeningBkg.png"))); // NOI18N
        registerPanel.add(backgroundLogInImage1);
        backgroundLogInImage1.setBounds(0, 0, 800, 770);

        mainPanel.add(registerPanel, "registerPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void easyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyBtnActionPerformed
        // When button is pressed we have to change the panel to the Easy Levels Panel
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "easyLevelsPanel");
    }//GEN-LAST:event_easyBtnActionPerformed

    private void level4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level4BtnActionPerformed
        // When button is pressed we have to prepare the level to be displayed
        // The first step is to get the level itself
        e4.PrepareWindow(this);
        
        // Store level in another variable
        level = e4;
        
        // Then we prepare the window
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "levelPanel");
    }//GEN-LAST:event_level4BtnActionPerformed

    private void level8BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level8BtnActionPerformed
        // When button is pressed we have to prepare the level to be displayed
        // The first step is to get the level itself
        e8.PrepareWindow(this);
        
        // Store level in another variable
        level = e8;
        
        // Then we prepare the window
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "levelPanel");
    }//GEN-LAST:event_level8BtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // When button is pressed we have to change the panel to the Opening Window Panel
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "openingMenuPanel");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void level4Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level4Btn1ActionPerformed
        // When button is pressed we have to prepare the level to be displayed
        // The first step is to get the level itself
        h4.PrepareWindow(this);
        
        // Save level in another variable
        level = h4;
        
        // Then we prepare the window
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "levelPanel");
    }//GEN-LAST:event_level4Btn1ActionPerformed

    private void level8Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level8Btn1ActionPerformed
        // When button is pressed we have to prepare the level to be displayed
        // The first step is to get the level itself
        h8.PrepareWindow(this);
        
        // Save level in another variable
        level = h8;
        
        // Then we prepare the window
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "levelPanel");
    }//GEN-LAST:event_level8Btn1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // When button is pressed we have to change the panel to the Opening Window Panel
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "openingMenuPanel");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void hardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardBtnActionPerformed
        // When button is pressed we have to change the panel to the Hard Levels Panel
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "hardLevelsPanel");
    }//GEN-LAST:event_hardBtnActionPerformed

    private void level1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level1BtnActionPerformed
        // When button is pressed we have to prepare the level to be displayed
        // The first step is to get the level itself
        e1.PrepareWindow(this);
        
        // Store level in another variable
        level = e1;
        
        // Then we prepare the window
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "levelPanel");
    }//GEN-LAST:event_level1BtnActionPerformed

    private void number7SquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number7SquareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_number7SquareActionPerformed

    private void checkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBtnActionPerformed
        // Since this button is used for both checking and advancing to the next level we have to first check what the button is gonna do
        if(this.checkBtn.getText().equals("Check Answers"))
        {
            // Add one to the games played
            if(isLogged)
            {
                player.gamePlayed();
            }

            // To make sure the program doesnt crash, we use a try catch so that if it is empty it'll give an error when creating the object
            try
            {
                // When the player presses the check answers button we first have to creat a level object with the user data to use to compare to the actual level
                int n1 = Integer.parseInt(number1Square.getText());
                int n2 = Integer.parseInt(number2Square.getText());
                int n3 = Integer.parseInt(number3Square.getText());
                int n4 = Integer.parseInt(number4Square.getText());
                int n5 = Integer.parseInt(number5Square.getText());
                int n6 = Integer.parseInt(number6Square.getText());
                int n7 = Integer.parseInt(number7Square.getText());
                int n8 = Integer.parseInt(number8Square.getText());
                int n9 = Integer.parseInt(number9Square.getText());
                int n10 = Integer.parseInt(number10Square.getText());
                int n11 = Integer.parseInt(number11Square.getText());
                int n12 = Integer.parseInt(number12Square.getText());
                int n13 = Integer.parseInt(number13Square.getText());
                int n14 = Integer.parseInt(number14Square.getText());
                int n15 = Integer.parseInt(number15Square.getText());

                // The player level object does not need any ID, difficulty, or sign, just the number values
                Level playerLevel = new Level("","","", n1, n2, n3, n4, n5, n6, n7, n8, n9, n10, n11, n12, n13, n14, n15);

                // Now that we have the player object, we can call the checkAnswers method in the actual level object
                if(level.checkAnswers(playerLevel, this))
                {
                    // If the answers the player introduced were correct, then we display congrats message and give the player the option to play the next level
                    this.levelInformationLabel.setText("<html>CONGRATs<br/>You can now proceed to the next level!</html>");
                    if(isLogged)
                    {
                        player.gameWon();
                    }
                    
                    // Now we need to unlock the next level
                    unlockLevel(level.getLevelID());
                    
                    // Finally we change the text on the button
                    this.checkBtn.setText("Next Level");
                    
                }
                else
                {
                    // If there is at least one wrong answer, then we give the player the option to replay the level and update the information
                    this.levelInformationLabel.setText("<html>OH NO!<br/>Some of your answers are wrong.</html>");
                    this.checkBtn.setText("Replay");
                }
            }
            catch(Exception e)
            {
                // If the player hasn't introduced all of the number needed, then we give a message asking the player to introduce a number on every space
                this.levelInformationLabel.setText("<html>Make sure you fill every space before checking the answers!</html>");
            }
            
            if(isLogged)
            {
                updateNumbers();
            }
        }
        else if(this.checkBtn.getText().equals("Replay"))
        {
            // If the player choses to replay the level all we have to do is prepare the window for the player again
            level.PrepareWindow(this);
        }
        
        else
        {
            // If the player choses to play the next level them all we have to do is do prepare the window for the player to see
            // The first step is to identify the current level so we can prepare the next level accordingly
            if(level.getLevelID().equals("1E"))
            {
                e2.PrepareWindow(this);

                // Save level in another variable
                level = e2;   
            }
            else if(level.getLevelID().equals("2E"))
            {
                e3.PrepareWindow(this);

                // Save level in another variable
                level = e3;  
            }
        }    
    }//GEN-LAST:event_checkBtnActionPerformed

    private void level1Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level1Btn1ActionPerformed
        // When button is pressed we have to prepare the level to be displayed
        // The first step is to get the level itself
        h1.PrepareWindow(this);
        
        // Save level in another variable
        level = h1;
        
        // Then we prepare the window
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "levelPanel");
    }//GEN-LAST:event_level1Btn1ActionPerformed

    private void goBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackBtnActionPerformed
        // Button to go back to the level select
        CardLayout card = (CardLayout)mainPanel.getLayout();

        if(level.getDifficulty().equals("Easy"))
        {
            // If the level is easy go back to the easy level selection
            card.show(mainPanel, "easyLevelsPanel");
        }
        else
        {
            // If the level is hard go back to the easy level selection
            card.show(mainPanel, "hardLevelsPanel");
        }
    }//GEN-LAST:event_goBackBtnActionPerformed

    private void level2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level2BtnActionPerformed
        // When button is pressed we have to prepare the level to be displayed
        // The first step is to get the level itself
        e2.PrepareWindow(this);
        
        // Save level in another variable
        level = e2;
        
        // Then we prepare the window
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "levelPanel");
    }//GEN-LAST:event_level2BtnActionPerformed

    private void level3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level3BtnActionPerformed
        // When button is pressed we have to prepare the level to be displayed
        // The first step is to get the level itself
        e3.PrepareWindow(this);
        
        // Save level in another variable
        level = e3;
        
        // Then we prepare the window
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "levelPanel");
    }//GEN-LAST:event_level3BtnActionPerformed

    private void logInPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInPanelBtnActionPerformed
        // This button is responsible to manage the user virtual identity
        // The default text on the button is "Log In"
        // Once the button has this text then we need to present the log in panel
        if(this.logInPanelBtn.getText().equals("Log In"))
        {
            this.usernameTxtLogInPanel.setText("");
            this.passwordTxtLogInPanel.setText("");
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "logInPanel");
        }
        // If the button has the text "My Profile" then it has to show the profile panel
        if(this.logInPanelBtn.getText().equals("My Profile"))
        {
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "profilePanel");
        }
    }//GEN-LAST:event_logInPanelBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // When this button is pressed we have to diplay the log in panel
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "openingMenuPanel");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "openingMenuPanel");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "logInPanel");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void logInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInBtnActionPerformed
        // This button is used to call the methods necessary for the user to log in

        // First we need to retrieve the password the user introduced and convert it into a String
        String passText = new String(passwordTxtLogInPanel.getPassword());

        // Then we create a new player object, where we store the username and the string password
        player = new Player(usernameTxtLogInPanel.getText(), passText);

        // Finally once we get the player object ready, we call the logIn method on the Database class to check the password and, if it matches, retrieve the player information
        // This method is going to return a boolean value. If it returns true then it means we can proccedd to make the necessary adjustments to the game
        if(db.logIn(player))
        {
            isLogged = true;
            presentLogIn();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "The Program wasn't able to log you in.");
        }

        // Finally we go back to the main window
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "openingMenuPanel");
    }//GEN-LAST:event_logInBtnActionPerformed

    private void registerPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPanelBtnActionPerformed
        // TODO add your handling code here:
        this.usernameTxtLogInPanel1.setText("");
        this.passwordTxtLogInPanel1.setText("");
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "registerPanel");
    }//GEN-LAST:event_registerPanelBtnActionPerformed

    private void registerPanelBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPanelBtn1ActionPerformed
        // TODO add your handling code here:
        // First we need to retrieve the password the user introduced and convert it into a String
        String passText = new String(passwordTxtLogInPanel1.getPassword());
        
        System.out.println(passText);

        // Then we create a new player object, where we store the username and the string password
        player = new Player(usernameTxtLogInPanel1.getText(), passText);
        
        try
        {
            player.createAccount();
            isLogged = true;
            presentLogIn();
        }
        catch(Exception e)
        {
            System.out.println(e);
            
        }

        // Finally we go back to the main window
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "openingMenuPanel");
    }//GEN-LAST:event_registerPanelBtn1ActionPerformed

    private void level5BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level5BtnActionPerformed
        // When button is pressed we have to prepare the level to be displayed
        // The first step is to get the level itself
        e5.PrepareWindow(this);
        
        // Store level in another variable
        level = e5;
        
        // Then we prepare the window
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "levelPanel");
    }//GEN-LAST:event_level5BtnActionPerformed

    private void level6BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level6BtnActionPerformed
        // When button is pressed we have to prepare the level to be displayed
        // The first step is to get the level itself
        e6.PrepareWindow(this);
        
        // Store level in another variable
        level = e6;
        
        // Then we prepare the window
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "levelPanel");
    }//GEN-LAST:event_level6BtnActionPerformed

    private void level7BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level7BtnActionPerformed
        // When button is pressed we have to prepare the level to be displayed
        // The first step is to get the level itself
        e7.PrepareWindow(this);
        
        // Store level in another variable
        level = e7;
        
        // Then we prepare the window
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "levelPanel");
    }//GEN-LAST:event_level7BtnActionPerformed

    private void level2Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level2Btn1ActionPerformed
        // When button is pressed we have to prepare the level to be displayed
        // The first step is to get the level itself
        h2.PrepareWindow(this);
        
        // Save level in another variable
        level = h2;
        
        // Then we prepare the window
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "levelPanel");
    }//GEN-LAST:event_level2Btn1ActionPerformed

    private void level3Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level3Btn1ActionPerformed
        // When button is pressed we have to prepare the level to be displayed
        // The first step is to get the level itself
        h3.PrepareWindow(this);
        
        // Save level in another variable
        level = h3;
        
        // Then we prepare the window
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "levelPanel");
    }//GEN-LAST:event_level3Btn1ActionPerformed

    private void level5Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level5Btn1ActionPerformed
        // When button is pressed we have to prepare the level to be displayed
        // The first step is to get the level itself
        h5.PrepareWindow(this);
        
        // Save level in another variable
        level = h5;
        
        // Then we prepare the window
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "levelPanel");
    }//GEN-LAST:event_level5Btn1ActionPerformed

    private void level6Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level6Btn1ActionPerformed
        // When button is pressed we have to prepare the level to be displayed
        // The first step is to get the level itself
        h6.PrepareWindow(this);
        
        // Save level in another variable
        level = h6;
        
        // Then we prepare the window
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "levelPanel");
    }//GEN-LAST:event_level6Btn1ActionPerformed

    private void level7Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level7Btn1ActionPerformed
        // When button is pressed we have to prepare the level to be displayed
        // The first step is to get the level itself
        h7.PrepareWindow(this);
        
        // Save level in another variable
        level = h7;
        
        // Then we prepare the window
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "levelPanel");
    }//GEN-LAST:event_level7Btn1ActionPerformed
    
    public void unlockLevel(String ln)
    {
        // This method is used to unlock levels
        if(ln.equals("1E"))
        {
            this.level2Btn.setEnabled(true);
            player.setE2(true);
            this.e2Unlocked.setIcon(new ImageIcon(getClass().getResource("GreenCircle.png")));
            db.unlockLevel("E2", player.getUserName());
        }
        else if(ln.equals("2E"))
        {
            this.level3Btn.setEnabled(true);
            player.setE3(true);
            this.e3Unlocked.setIcon(new ImageIcon(getClass().getResource("GreenCircle.png")));
            db.unlockLevel("E3", player.getUserName());
        }
        else if(ln.equals("3E"))
        {
            this.level4Btn.setEnabled(true);
            player.setE4(true);
            this.e4Unlocked.setIcon(new ImageIcon(getClass().getResource("GreenCircle.png")));
            db.unlockLevel("E4", player.getUserName());
        }
        else if(ln.equals("4E"))
        {
            this.level5Btn.setEnabled(true);
            player.setE5(true);
            this.e5Unlocked.setIcon(new ImageIcon(getClass().getResource("GreenCircle.png")));
            db.unlockLevel("E5", player.getUserName());
        }
        else if(ln.equals("5E"))
        {
            this.level6Btn.setEnabled(true);
            player.setE6(true);
            this.e6Unlocked.setIcon(new ImageIcon(getClass().getResource("GreenCircle.png")));
            db.unlockLevel("E6", player.getUserName());
        }
        else if(ln.equals("6E"))
        {
            this.level7Btn.setEnabled(true);
            player.setE7(true);
            this.e7Unlocked.setIcon(new ImageIcon(getClass().getResource("GreenCircle.png")));
            db.unlockLevel("E7", player.getUserName());
        }
        else if(ln.equals("7E"))
        {
            this.level8Btn.setEnabled(true);
            player.setE8(true);
            this.e8Unlocked.setIcon(new ImageIcon(getClass().getResource("GreenCircle.png")));
            db.unlockLevel("E8", player.getUserName());
        }
        else if(ln.equals("1H"))
        {
            this.level2Btn1.setEnabled(true);
            player.setH2(true);
            this.h2Unlocked.setIcon(new ImageIcon(getClass().getResource("GreenCircle.png")));
            db.unlockLevel("H2", player.getUserName());
        }
        else if(ln.equals("2H"))
        {
            this.level3Btn1.setEnabled(true);
            player.setH3(true);
            this.h3Unlocked.setIcon(new ImageIcon(getClass().getResource("GreenCircle.png")));
            db.unlockLevel("H3", player.getUserName());
        }
        else if(ln.equals("3H"))
        {
            this.level4Btn1.setEnabled(true);
            player.setH4(true);
            this.h4Unlocked.setIcon(new ImageIcon(getClass().getResource("GreenCircle.png")));
            db.unlockLevel("H4", player.getUserName());
        }
        else if(ln.equals("4H"))
        {
            this.level5Btn1.setEnabled(true);
            player.setH5(true);
            this.h5Unlocked.setIcon(new ImageIcon(getClass().getResource("GreenCircle.png")));
            db.unlockLevel("H5", player.getUserName());
        }
        else if(ln.equals("5H"))
        {
            this.level6Btn1.setEnabled(true);
            player.setH6(true);
            this.h6Unlocked.setIcon(new ImageIcon(getClass().getResource("GreenCircle.png")));
            db.unlockLevel("H6", player.getUserName());
        }
        else if(ln.equals("6H"))
        {
            this.level7Btn1.setEnabled(true);
            player.setH7(true);
            this.h7Unlocked.setIcon(new ImageIcon(getClass().getResource("GreenCircle.png")));
            db.unlockLevel("H7", player.getUserName());
        }
        else if(ln.equals("7H"))
        {
            this.level8Btn1.setEnabled(true);
            player.setH8(true);
            this.h8Unlocked.setIcon(new ImageIcon(getClass().getResource("GreenCircle.png")));
            db.unlockLevel("H8", player.getUserName());
        }
    }
    public void presentLogIn()
    {
        // After we logged in an retrieved the data from the database we need to prepare the program to be correctly diplayed
        
        // First we need to change the log in button to a button that will display a panel with the information about the user's profile
        this.logInPanelBtn.setText("My Profile");
        this.logInLabel.setText("Wellcome, " + player.getUserName());
        
        // Now we have to correctly unlock the levels the user has unlocked
        if(player.getE2())
        {
            unlockLevel("1E");
        }
        else
        {
            this.level2Btn.setEnabled(false);
            this.e2Unlocked.setIcon(new ImageIcon(getClass().getResource("RedCircle.png")));
        }
        if(player.getE3())
        {
            unlockLevel("2E");
        }
        else
        {
            this.level3Btn.setEnabled(false);
            this.e3Unlocked.setIcon(new ImageIcon(getClass().getResource("RedCircle.png")));
        }
        if(player.getE4())
        {
            unlockLevel("3E");
        }
        else
        {
            this.level4Btn.setEnabled(false);
            this.e4Unlocked.setIcon(new ImageIcon(getClass().getResource("RedCircle.png")));
        }
        if(player.getE5())
        {
            unlockLevel("4E");
        }
        else
        {
            this.level5Btn.setEnabled(false);
            this.e5Unlocked.setIcon(new ImageIcon(getClass().getResource("RedCircle.png")));
        }
        if(player.getE6())
        {
            unlockLevel("5E");
        }
        else
        {
            this.level6Btn.setEnabled(false);
            this.e6Unlocked.setIcon(new ImageIcon(getClass().getResource("RedCircle.png")));
        }
        if(player.getE7())
        {
            unlockLevel("6E");
        }
        else
        {
            this.level7Btn.setEnabled(false);
            this.e7Unlocked.setIcon(new ImageIcon(getClass().getResource("RedCircle.png")));
        }
        if(player.getE8())
        {
            unlockLevel("7E");
        }
        else
        {
            this.level8Btn.setEnabled(false);
            this.e8Unlocked.setIcon(new ImageIcon(getClass().getResource("RedCircle.png")));
        }
        if(player.getH2())
        {
            unlockLevel("1H");
        }
        else
        {
            this.level2Btn1.setEnabled(false);
            this.h2Unlocked.setIcon(new ImageIcon(getClass().getResource("RedCircle.png")));
        }
        if(player.getH3())
        {
            unlockLevel("2H");
        }
        else
        {
            this.level3Btn1.setEnabled(false);
            this.h3Unlocked.setIcon(new ImageIcon(getClass().getResource("RedCircle.png")));
        }
        if(player.getH4())
        {
            unlockLevel("3H");
        }
        else
        {
            this.level4Btn1.setEnabled(false);
            this.h4Unlocked.setIcon(new ImageIcon(getClass().getResource("RedCircle.png")));
        }
        if(player.getH5())
        {
            unlockLevel("4H");
        }
        else
        {
            this.level6Btn1.setEnabled(false);
            this.h5Unlocked.setIcon(new ImageIcon(getClass().getResource("RedCircle.png")));
        }
        if(player.getH6())
        {
            unlockLevel("5H");
        }
        else
        {
            this.level5Btn1.setEnabled(false);
            this.h6Unlocked.setIcon(new ImageIcon(getClass().getResource("RedCircle.png")));
        }
        if(player.getH7())
        {
            unlockLevel("6H");
        }
        else
        {
            this.level7Btn1.setEnabled(false);
            this.h7Unlocked.setIcon(new ImageIcon(getClass().getResource("RedCircle.png")));
        }
        if(player.getH8())
        {
            unlockLevel("7H");
        }
        else
        {
            this.level8Btn1.setEnabled(false);
            this.h8Unlocked.setIcon(new ImageIcon(getClass().getResource("RedCircle.png")));
        }
        
        // Lastly we change the information on the profile panel
        this.userNameLabel.setText(player.getUserName());
        
        // COUNTRY FLAG STILL NEEDS TO BE DONE
        try
        {
            this.countryFlag.setIcon(new ImageIcon(getClass().getResource(player.getCountry() + ".png")));
        }
        catch(Exception e)
        {
            this.countryFlag.setIcon(new ImageIcon(getClass().getResource("UN.png")));
        }
        
        updateNumbers();
    }
    
    public void updateNumbers()
    {
        // Set the games played and won Double.toString(player.getGamesPlayed())
        this.playedTxt.setText(new DecimalFormat("###").format(player.getGamesPlayed()));
        this.wonTxt.setText(new DecimalFormat("###").format(player.getGamesWon()));
        
        double percentage = (player.getGamesWon()/player.getGamesPlayed())*100;
        this.percentageTxt.setText(new DecimalFormat("###").format(percentage) + "%");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpeningForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpeningForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpeningForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpeningForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpeningForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundELImage;
    private javax.swing.JLabel backgroundELImage1;
    private javax.swing.JLabel backgroundLevelPanel;
    private javax.swing.JLabel backgroundLogInImage;
    private javax.swing.JLabel backgroundLogInImage1;
    private javax.swing.JLabel backgroundOMImage;
    private javax.swing.JLabel backgroundProfileImage;
    public javax.swing.JButton checkBtn;
    private javax.swing.JLabel countryFlag;
    private javax.swing.JLabel e1Unlocked;
    private javax.swing.JLabel e2Unlocked;
    private javax.swing.JLabel e3Unlocked;
    private javax.swing.JLabel e4Unlocked;
    private javax.swing.JLabel e5Unlocked;
    private javax.swing.JLabel e6Unlocked;
    private javax.swing.JLabel e7Unlocked;
    private javax.swing.JLabel e8Unlocked;
    private javax.swing.JButton easyBtn;
    private javax.swing.JPanel easyLevelsPanel;
    public javax.swing.JButton goBackBtn;
    private javax.swing.JLabel h1Unlocked;
    private javax.swing.JLabel h2Unlocked;
    private javax.swing.JLabel h3Unlocked;
    private javax.swing.JLabel h4Unlocked;
    private javax.swing.JLabel h5Unlocked;
    private javax.swing.JLabel h6Unlocked;
    private javax.swing.JLabel h7Unlocked;
    private javax.swing.JLabel h8Unlocked;
    private javax.swing.JButton hardBtn;
    private javax.swing.JPanel hardLevelsPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton level1Btn;
    private javax.swing.JButton level1Btn1;
    private javax.swing.JButton level2Btn;
    private javax.swing.JButton level2Btn1;
    private javax.swing.JButton level3Btn;
    private javax.swing.JButton level3Btn1;
    private javax.swing.JButton level4Btn;
    private javax.swing.JButton level4Btn1;
    private javax.swing.JButton level5Btn;
    private javax.swing.JButton level5Btn1;
    private javax.swing.JButton level6Btn;
    private javax.swing.JButton level6Btn1;
    private javax.swing.JButton level7Btn;
    private javax.swing.JButton level7Btn1;
    private javax.swing.JButton level8Btn;
    private javax.swing.JButton level8Btn1;
    public javax.swing.JLabel levelInformationLabel;
    public javax.swing.JLabel levelLabel;
    private javax.swing.JPanel levelPanel;
    private javax.swing.JButton logInBtn;
    private javax.swing.JLabel logInLabel;
    private javax.swing.JPanel logInPanel;
    private javax.swing.JButton logInPanelBtn;
    public javax.swing.JPanel mainPanel;
    public javax.swing.JTextField number10Square;
    public javax.swing.JTextField number11Square;
    public javax.swing.JTextField number12Square;
    public javax.swing.JTextField number13Square;
    public javax.swing.JTextField number14Square;
    public javax.swing.JTextField number15Square;
    public javax.swing.JTextField number1Square;
    public javax.swing.JTextField number2Square;
    public javax.swing.JTextField number3Square;
    public javax.swing.JTextField number4Square;
    public javax.swing.JTextField number5Square;
    public javax.swing.JTextField number6Square;
    public javax.swing.JTextField number7Square;
    public javax.swing.JTextField number8Square;
    public javax.swing.JTextField number9Square;
    private javax.swing.JPanel openingMenuPanel;
    private javax.swing.JLabel passwordLogInPanel;
    private javax.swing.JLabel passwordLogInPanel1;
    public javax.swing.JPasswordField passwordTxtLogInPanel;
    public javax.swing.JPasswordField passwordTxtLogInPanel1;
    private javax.swing.JLabel percentageTxt;
    private javax.swing.JLabel playedTxt;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JButton registerPanelBtn;
    private javax.swing.JButton registerPanelBtn1;
    public javax.swing.JTextField signSquare;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JLabel usernameLogInPanel;
    private javax.swing.JLabel usernameLogInPanel1;
    public javax.swing.JTextField usernameTxtLogInPanel;
    public javax.swing.JTextField usernameTxtLogInPanel1;
    private javax.swing.JLabel wonTxt;
    // End of variables declaration//GEN-END:variables
}
